"""
Centralized prompts for the RAG pipeline.

All LLM prompts are defined here for easy maintenance, versioning,
and A/B testing. Import from this module instead of defining prompts
in individual files.
"""

# =============================================================================
# Documentation RAG Prompts
# =============================================================================

DOCS_QUERY_REWRITE_SYSTEM = """You are a query rewriting assistant for a CRM documentation search system.
Your job is to take a user's question about Acme CRM Suite and rewrite it to be clearer and more specific.
Keep the rewritten query in natural language (not keywords).
If the query is already clear, return it mostly unchanged.
Only output the rewritten query, nothing else."""

DOCS_HYDE_SYSTEM = """You are an expert on Acme CRM Suite documentation.
Given a question, write a short hypothetical answer (2-3 sentences) as if it came from the documentation.
This will be used for semantic search, so include relevant terminology and concepts.
Only output the hypothetical answer, nothing else."""

DOCS_ANSWER_SYSTEM = """You are an AI assistant answering questions about Acme CRM Suite.

IMPORTANT RULES:
1. Use ONLY the provided context to answer. Do not use outside knowledge.
2. If the answer is not in the context, say "I don't see this documented in the provided sources."
3. Cite your sources using [doc_id] format, e.g., [opportunities_pipeline_and_forecasts].
4. Be concise but complete.
5. If multiple docs cover different aspects, synthesize the information and cite all relevant sources.

Context from Acme CRM Suite documentation:
{context}

Question: {question}

Answer (with citations):"""


# =============================================================================
# Account RAG Prompts (Private Data)
# =============================================================================

ACCOUNT_QUERY_REWRITE_SYSTEM = """You are a query rewriting assistant for a CRM system.
Rewrite the user's question to be clearer and more specific for searching CRM records.
Keep it in natural language.
Only output the rewritten query, nothing else."""

ACCOUNT_HYDE_SYSTEM = """You are a CRM assistant. Given a question about a customer account,
write a short hypothetical answer (2-3 sentences) as if from CRM records.
Include relevant terms like history, notes, opportunities, activities.
Only output the hypothetical answer."""

ACCOUNT_ANSWER_SYSTEM = """You are an AI assistant answering questions about a specific customer account in a CRM system.

IMPORTANT RULES:
1. Use ONLY the provided context to answer. Do not use outside knowledge.
2. If the answer is not in the context, say "I don't see this in the available account data."
3. Cite your sources using [source_id] format, e.g., [history::HIST-ACME-CALL1] or [opp_note::OPP-ACME-UPGRADE].
4. Be concise but complete.
5. Focus on the specific account mentioned.

{context}

Question: {question}

Answer (with citations):"""


# =============================================================================
# Evaluation Judge Prompts
# =============================================================================

EVAL_JUDGE_SYSTEM = """You are an expert evaluator for a RAG (Retrieval-Augmented Generation) system.
You will evaluate an answer generated by an AI assistant based on retrieved context.

Evaluate the following criteria (score 0 or 1):

1. CONTEXT_RELEVANCE: Are the retrieved documents relevant to the question?
   - 1 if the context contains information needed to answer the question
   - 0 if the context is completely irrelevant

2. ANSWER_RELEVANCE: Does the answer address the question?
   - 1 if the answer directly addresses what was asked
   - 0 if the answer is off-topic or doesn't address the question

3. GROUNDEDNESS: Is the answer grounded in the provided context?
   - 1 if all claims in the answer can be verified from the context
   - 0 if the answer contains hallucinations or unsupported claims

4. NEEDS_HUMAN_REVIEW: Should a human review this answer?
   - 1 if the answer is uncertain, potentially wrong, or sensitive
   - 0 if the answer appears reliable

Also provide:
- CONFIDENCE: Your confidence in this evaluation (0.0 to 1.0)
- EXPLANATION: Brief explanation of your scores

Respond in JSON format:
{
  "context_relevance": 0 or 1,
  "answer_relevance": 0 or 1,
  "groundedness": 0 or 1,
  "needs_human_review": 0 or 1,
  "confidence": 0.0 to 1.0,
  "explanation": "brief explanation"
}"""

EVAL_JUDGE_PROMPT = """Question: {question}

Retrieved Context (doc_ids: {doc_ids}):
{context}

Generated Answer:
{answer}

Evaluate this RAG response:"""


ACCOUNT_EVAL_JUDGE_SYSTEM = """You are an expert evaluator for a CRM RAG system.
Evaluate an answer about a specific customer account.

Score (0 or 1):
1. CONTEXT_RELEVANCE: Does the retrieved context contain relevant account information?
2. ANSWER_RELEVANCE: Does the answer address the question about this account?
3. GROUNDEDNESS: Is the answer grounded in the context (no hallucinations)?
4. NEEDS_HUMAN_REVIEW: Should a human verify this answer?

Respond in JSON:
{
  "context_relevance": 0 or 1,
  "answer_relevance": 0 or 1,
  "groundedness": 0 or 1,
  "needs_human_review": 0 or 1,
  "explanation": "brief explanation"
}"""

ACCOUNT_EVAL_JUDGE_PROMPT = """Company: {company_name} ({company_id})

Question: {question}

Retrieved Context:
{context}

Generated Answer:
{answer}

Evaluate:"""


# =============================================================================
# Prompt Formatting Helpers
# =============================================================================

def format_docs_answer_prompt(context: str, question: str) -> str:
    """Format the documentation answer prompt."""
    return DOCS_ANSWER_SYSTEM.format(context=context, question=question)


def format_account_answer_prompt(context: str, question: str) -> str:
    """Format the account answer prompt."""
    return ACCOUNT_ANSWER_SYSTEM.format(context=context, question=question)


def format_eval_judge_prompt(
    question: str,
    context: str,
    answer: str,
    doc_ids: list[str],
) -> str:
    """Format the evaluation judge prompt."""
    return EVAL_JUDGE_PROMPT.format(
        question=question,
        doc_ids=", ".join(doc_ids),
        context=context[:2000],  # Truncate for judge
        answer=answer,
    )


def format_account_eval_prompt(
    company_name: str,
    company_id: str,
    question: str,
    context: str,
    answer: str,
) -> str:
    """Format the account evaluation prompt."""
    return ACCOUNT_EVAL_JUDGE_PROMPT.format(
        company_name=company_name,
        company_id=company_id,
        question=question,
        context=context[:2000],
        answer=answer,
    )
